unstable_features = true

hard_tabs = true
newline_style = "Unix"

max_width = 100

format_code_in_doc_comments = true

imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
match_block_trailing_comma = true
overflow_delimited_expr = true
reorder_impl_items = true
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true
condense_wildcard_suffixes = true
