[package]
name = "dyntable-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "^2", features = ["full", "extra-traits"] }
quote = "^1"
proc-macro2 = "^1"
