name: Run Tests
on: push
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup nix
        uses: cachix/install-nix-action@v19

      - name: check formatting
        run: nix develop .# -c cargo fmt --check
      - name: check codegen formatting
        run: nix develop .# -c bash -c "cd dyntable-macro; cargo fmt --check"
      - name: check features > none
        run: nix develop .# -c cargo check --no-default-features
      - name: check features > alloc
        run: nix develop .# -c cargo check --no-default-features --features alloc
      - name: check features > std
        run: nix develop .# -c cargo check --no-default-features --features std
      - name: check features > allocator_api
        run: nix develop .# -c cargo check --no-default-features --features allocator_api
      - name: check features > allocator_api, alloc
        run: nix develop .# -c cargo check --no-default-features --features allocator_api --features alloc
      - name: check features > allocator_api, std
        run: nix develop .# -c cargo check --no-default-features --features allocator_api --features std
      - name: check macro crate
        run: nix develop .# -c cargo check --package dyntable-macro
      - name: run tests
        run: nix develop .#stable -c cargo test
      - name: run miri tests
        run: nix develop .# -c cargo miri test
